### ISSUE TITLE
Performance differences vs yojson

### ISSUE THREAD

**Issue by yminsky** [dbuenzli/jsonm#10]
For a number of reasons, I'd prefer to use jsonm rather than yojson, but yojson is considerably faster. We noticed this in some internal benchmarks, which tracked pretty closely what came up in this blog post:

http://rgrinberg.com/posts/ocaml-json-benchmark/

According to that post, it takes about 2x the time, and allocates maybe 25x as much. 

Is there any appetite for working performance of jsonm?

**Comment by dbuenzli** [comment]
AFAIR `yojson` doesn't check encoding validity so I guess `jsonm` is bound to be slower. 

Regarding allocation that's a bit surprising but I suppose is due to the internal continuation based monkey dance for supporting non-blocking scenarios. I'd gladly rewrite all this in direct style along [these lines](https://github.com/dbuenzli/nbcodec/blob/master/src/se.mli#L176-L245) once we have effects in the language...

But before that actually happens maybe a little bit of profiling might uncover some stupid pattern in the implementation.

**Comment by dbuenzli** [comment]
Also note sure exactly what your "reasons" are but  `jsonm` is quite precise with location tracking for error reporting. If you don't really care about that maybe @seliopou's angstrom based [json](https://github.com/inhabitedtype/angstrom/blob/master/examples/rFC7159.ml) decoder may be worth considering.

**Comment by yminsky** [comment]
That's an interesting idea. I'll check with @seliopou.

y

**Comment by dbuenzli** [comment]
Cool, if you end up benchmarking that aswell against `jsonm` I'm interested in hearing the results.

**Comment by NathanReb** [comment]
I'm curious, @yminsky have you tried writing parsers using `angstrom` in the end?

I was considering different parsers (including `jsonm`) and found this issue. We'd be interested in avoiding allocation of the json AST for performance reasons at Cryptosense as well so `angstrom` could prove useful for that.

The idea in the end would be to write a ppx to derive such json parsers/printers.

**Comment by yminsky** [comment]
@seliopou wrote such a parser, though we haven't open sourced it yet. He can say more, and I think we'd be happy to release it.

**Comment by seliopou** [comment]
Those parsers have actually always been open source. The original version is in the angstrom repository [here](https://github.com/inhabitedtype/angstrom/blob/master/examples/rFC7159.ml). Earlier this year I tweaked it a bit and put it into a separate repository called [jsonaf](https://github.com/inhabitedtype/jsonaf). It however has yet to seen an OPAM release.

**Comment by dbuenzli** [comment]
Since [jsont](https://erratique.ch/software/jsont) has been released, `jsonm` is in maintenance mode and will not be worked on any further. 

In case this is still of interest (I doubt :-), `jsont` seems to be faster on decoding to generic JSON than `yojson`, see [this unscientific benchmark](https://discuss.ocaml.org/t/ann-jsont-0-1-0-declarative-json-data-manipulation-for-ocaml/15702/2?u=dbuenzli).
